- route:
    id: route-3885
    description: Get request every 5s
    from:
      id: from-4847
      uri: timer:t
      parameters:
        period: 5000
      steps:
        - setHeader:
            id: setHeader-1867
            expression:
              constant:
                expression: "12345"
            name: customerId
        - to:
            id: to-4437
            uri: rest-openapi:api-registry/product-page-api.json#operationIdUpdateMe
            parameters:
              basePath: /api/v1
              host: https://product-page-bookinfo-dev.apps.cluster.com
        - log:
            id: log-3873
            message: ${body}